[tool.black]
line-length = 79

[tool.isort]
atomic = true
force_grid_wrap = 0
include_trailing_comma = true
lines_after_imports = 2
lines_between_types = 1
multi_line_output = 3
not_skip = "__init__.py"
use_parentheses = true
known_first_party = ["instances","models", "rde"]
known_third_party = ["innvestigate", "keras", "kerasadf", "lime", "matplotlib", "numpy", "scipy", "shap", "skimage", "statstream", "tensorflow", "tikzplotlib", "tqdm"]
